recall_preset:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: hdmi_matrix
    device_id:
      selector:
        device:
          integration: hdmi_matrix
    preset:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box

switch_input:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: hdmi_matrix
    device_id:
      selector:
        device:
          integration: hdmi_matrix
    output:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box
    input:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box

send_cec_command:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: hdmi_matrix
    device_id:
      selector:
        device:
          integration: hdmi_matrix
    port_type:
      required: true
      default: input
      selector:
        select:
          translation_key: port_type
          options:
            - input
            - output
    port_num:
      required: true
      selector:
        number:
          min: 1
          max: 8
          mode: box
    command:
      required: true
      example: power_on
      selector:
        select:
          translation_key: cec_command
          options:
            - power_on
            - power_off
            - up
            - left
            - select
            - right
            - menu
            - down
            - back
            - previous
            - play
            - next
            - rewind
            - pause
            - fast_forward
            - stop
            - mute
            - volume_down
            - volume_up
            - active
